### ISSUE TITLE
Missing copyright notices

### ISSUE THREAD

**Issue by twesterhout** [pedromartins4/memo-AG#1]
As per the [GPL guidelines](https://www.gnu.org/licenses/gpl-howto.en.html) one should
> Give each file the proper copyright notices. 

A template for such a notice can be found in the LICENSE file itself: https://github.com/pedromartins4/memo-AG/blob/master/LICENSE#L623

Such copyright notices are missing in all (I think) Haskell source files.

**Comment by pedromartins4** [comment]
Thanks for pointing this out. The problem is fixed.
